import Vue from 'vue'
import {MLInstaller, MLCreate, MLanguage} from 'vue-multilanguage'

Vue.use(MLInstaller);

export default new MLCreate({
  initial: 'ar',
  // development  , production
  save: process.env.NODE_ENV === 'development',
  languages: [
    new MLanguage('en').create({
      ar: 'Arabic language',
      en: 'Arabic language',
      notification: 'Notification',
      settings: 'Settings',
      search: 'Search',
      add: 'Add',
      edit: 'Edit',
      dashboard: 'dashboard',
      lecturer: 'lecturer Management',
      loading: 'Loading ...',
      add_lecturer: 'Add Lecturer',
      edit_lecturer: 'Edit Lecturer',
      id: 'ID',
      name: 'Name',
      sec_section: 'secondary sections',
      add_sec_section: 'Add secondary section',
      edit_sec_section: 'Edit secondary section',
      country_section: 'Country sections',
      country: 'Country',
      add_country: 'Add Country',
      edit_country: 'Edit Country',
      government: 'Government',
      add_government: 'Add Government',
      edit_government: 'Edit Government',
      program: 'Program Management',
      add_program: 'Add Program',
      edit_program: 'Edit Program',
      hours_need_grade: 'Hours Needed To Graduate',
      min_number_grade: 'Min Number Per Term To Graduate',
      max_fail_percent: 'Max Fail Percent In Success State',
    }),

    new MLanguage('ar').create({
      ar: 'اللغة الانجليزية',
      en: 'اللغة الانجليزية',
      notification: 'الاشعارات',
      settings: 'الاعدادات',
      search: 'البحث',
      add: 'اضافة',
      edit: 'تعديل',
      dashboard: 'لوحة التحكم',
      lecturer: 'قسم المحاضرين',
      loading: 'جاري التحميل',
      add_lecturer: 'اضافة محاضر',
      edit_lecturer: 'تعديل محاضر',
      id: 'رقم مسلسل',
      name: 'الاسم',
      sec_section: 'اقسام الثانوية العامة',
      add_sec_section: 'اضافة قسم الثانوية العامة',
      edit_sec_section: 'تعديل قسم الثانوية العامة',
      country_section: 'البلاد و المحافظات',
      country: 'الدولة',
      add_country: 'اضافة دولة',
      edit_country: 'تعديل دولة',
      government: 'المحافظة',
      add_government: 'اضافة محافظة',
      edit_government: 'تعديل محافظة',
      program: 'ادارة  البرامج',
      add_program: 'اضافة برنامج',
      edit_program: 'تعديل برنامج',
      hours_need_grade: 'عدد الساعات المطلوبة للتخرج',
      min_number_grade: 'اقل عدد فى الترم للتخرج',
      max_fail_percent: 'اقصي نسبة لمادة الرسوب عند النجاح فيها',
    })
  ]
})
